### ISSUE TITLE
failed to build the program directly by pip

### ISSUE THREAD

**Issue by geohaolg** [CNES/shareloc#2]
* Date you used Cookiecutter PyPackage:
* Cookiecutter version used, if any:
* Python version, if any:
* Operating System: windows

### Description

cannot use `pip install` shareloc to build the program, even I checked all the dependencies.

### What I Did
(base) PS F:\codes\code-repo\shareloc> pip install shareloc
Collecting shareloc
  Using cached shareloc-0.2.1.tar.gz (29.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17.0 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (1.26.4)
Requirement already satisfied: scipy!=1.10.0,>=1.7.1 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (1.13.1)
Collecting rasterio (from shareloc)
  Using cached rasterio-1.3.10-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: xarray in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (2023.6.0)
Requirement already satisfied: numba in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (0.59.1)
Requirement already satisfied: pybind11 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (2.13.1)
Requirement already satisfied: pyarrow in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from shareloc) (14.0.2)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from numba->shareloc) (0.42.0)
Collecting affine (from rasterio->shareloc)
  Using cached affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: attrs in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from rasterio->shareloc) (23.1.0)
Requirement already satisfied: certifi in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from rasterio->shareloc) (2024.6.2)
Requirement already satisfied: click>=4.0 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from rasterio->shareloc) (8.1.7)
Collecting cligj>=0.5 (from rasterio->shareloc)
  Using cached cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)
Collecting snuggs>=1.4.1 (from rasterio->shareloc)
  Using cached snuggs-1.4.7-py3-none-any.whl.metadata (3.4 kB)
Collecting click-plugins (from rasterio->shareloc)
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: setuptools in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from rasterio->shareloc) (69.5.1)
Requirement already satisfied: pandas>=1.4 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from xarray->shareloc) (2.2.2)
Requirement already satisfied: packaging>=21.3 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from xarray->shareloc) (23.2)
Requirement already satisfied: colorama in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from click>=4.0->rasterio->shareloc) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from pandas>=1.4->xarray->shareloc) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from pandas>=1.4->xarray->shareloc) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from pandas>=1.4->xarray->shareloc) (2023.3)
Requirement already satisfied: pyparsing>=2.1.6 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from snuggs>=1.4.1->rasterio->shareloc) (3.0.9)
Requirement already satisfied: six>=1.5 in e:\scoop\apps\anaconda3\current\app\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.4->xarray->shareloc) (1.16.0)
Using cached rasterio-1.3.10-cp312-cp312-win_amd64.whl (24.3 MB)
Using cached cligj-0.7.2-py3-none-any.whl (7.1 kB)
Using cached snuggs-1.4.7-py3-none-any.whl (5.4 kB)
Using cached affine-2.4.0-py3-none-any.whl (15 kB)
Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Building wheels for collected packages: shareloc
  Building wheel for shareloc (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for shareloc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\shareloc
      copying shareloc\dtm_reader.py -> build\lib.win-amd64-cpython-312\shareloc
      copying shareloc\image.py -> build\lib.win-amd64-cpython-312\shareloc
      copying shareloc\math_utils.py -> build\lib.win-amd64-cpython-312\shareloc
      copying shareloc\proj_utils.py -> build\lib.win-amd64-cpython-312\shareloc
      copying shareloc\__init__.py -> build\lib.win-amd64-cpython-312\shareloc
      creating build\lib.win-amd64-cpython-312\tests
      copying tests\conftest.py -> build\lib.win-amd64-cpython-312\tests
      copying tests\helpers.py -> build\lib.win-amd64-cpython-312\tests
      copying tests\test_dtm_image.py -> build\lib.win-amd64-cpython-312\tests
      copying tests\test_image.py -> build\lib.win-amd64-cpython-312\tests
      copying tests\test_proj_utils.py -> build\lib.win-amd64-cpython-312\tests
      copying tests\__init__.py -> build\lib.win-amd64-cpython-312\tests
      creating build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\dtm_intersection.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\localization.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\rectification.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\rectification_grid.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\triangulation.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      copying shareloc\geofunctions\__init__.py -> build\lib.win-amd64-cpython-312\shareloc\geofunctions
      creating build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\geomodel.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\geomodel_template.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\grid.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\los.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\rpc.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\rpc_optim.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\rpc_readers.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      copying shareloc\geomodels\__init__.py -> build\lib.win-amd64-cpython-312\shareloc\geomodels
      creating build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_dtm_intersection.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_dtm_intersection_optim.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_localization.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_localization_optim.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_rectification.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_rectification_optim.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_strip_rectification_grid.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\test_triangulation.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      copying tests\geofunctions\__init__.py -> build\lib.win-amd64-cpython-312\tests\geofunctions
      creating build\lib.win-amd64-cpython-312\tests\geomodels
      copying tests\geomodels\test_grid.py -> build\lib.win-amd64-cpython-312\tests\geomodels
      copying tests\geomodels\test_los.py -> build\lib.win-amd64-cpython-312\tests\geomodels
      copying tests\geomodels\test_rpc.py -> build\lib.win-amd64-cpython-312\tests\geomodels
      copying tests\geomodels\test_rpc_optim.py -> build\lib.win-amd64-cpython-312\tests\geomodels
      copying tests\geomodels\__init__.py -> build\lib.win-amd64-cpython-312\tests\geomodels
      running build_ext
      building 'bindings_cpp' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\shareloc
      creating build\temp.win-amd64-cpython-312\Release\shareloc\bindings
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\haolong\AppData\Local\Temp\pip-build-env-poj5042l\overlay\Lib\site-packages\pybind11\include -IE:\scoop\apps\anaconda3\current\App\include -IE:\scoop\apps\anaconda3\current\App\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpshareloc/bindings/GeoModelTemplate.cpp /Fobuild\temp.win-amd64-cpython-312\Release\shareloc/bindings/GeoModelTemplate.obj /std:c++latest /EHsc /bigobj -O3
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      GeoModelTemplate.cpp
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\haolong\AppData\Local\Temp\pip-build-env-poj5042l\overlay\Lib\site-packages\pybind11\include -IE:\scoop\apps\anaconda3\current\App\include -IE:\scoop\apps\anaconda3\current\App\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpshareloc/bindings/bind.cpp /Fobuild\temp.win-amd64-cpython-312\Release\shareloc/bindings/bind.obj /std:c++latest /EHsc /bigobj -O3
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      bind.cpp
      C:\Users\haolong\AppData\Local\Temp\pip-install-et5fgmy3\shareloc_2d56832449374563a0a8d51ca8298f59\shareloc\bindings\rectification.cpp(46): error C2065: 'M_PI': undeclared identifier
      C:\Users\haolong\AppData\Local\Temp\pip-install-et5fgmy3\shareloc_2d56832449374563a0a8d51ca8298f59\shareloc\bindings\rectification.cpp(49): error C2065: 'M_PI': undeclared identifier
      C:\Users\haolong\AppData\Local\Temp\pip-install-et5fgmy3\shareloc_2d56832449374563a0a8d51ca8298f59\shareloc\bindings\rectification.cpp(62): error C2065: 'M_PI': undeclared identifier
      C:\Users\haolong\AppData\Local\Temp\pip-install-et5fgmy3\shareloc_2d56832449374563a0a8d51ca8298f59\shareloc\bindings\rectification.cpp(92): error C2065: 'M_PI': undeclared identifier
      C:\Users\haolong\AppData\Local\Temp\pip-install-et5fgmy3\shareloc_2d56832449374563a0a8d51ca8298f59\shareloc\bindings\rectification.cpp(92): error C3861: 'M_PI': identifier not found
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shareloc
Failed to build shareloc
ERROR: Could not build wheels for shareloc, which is required to install pyproject.toml-based projects

**Comment by dyoussef** [comment]
Hello @geohaolg,

This commit should solve the problem: https://github.com/CNES/shareloc/commit/7779d46cd9c6b081330068607a623aba612006e9

Can you clone the repository and check that it works? 
I can quickly push a new version to pypi.

Regards,
David

**Comment by geohaolg** [comment]
It works. I can successfully build the program by cloning the repository.
But there is a little bit inconvenience that I must modify the makefile to accommodate my venv settings(my system is win-64): it is `venv/Scripts/activate`,  not `venv/bin/activate`
Thanks a lot!

**Comment by dyoussef** [comment]
Thanks for checking @geohaolg. The new release is now available: https://pypi.org/project/shareloc/0.2.2/
